version: 2.1

orbs:
  maven: circleci/maven@1.0.1
jobs:
  git:
    steps:
      - run: git config user.email "lmdbluis@gmail.com"
      - run: git config user.name "Via circleci build"
workflows:
  maven_test:
    jobs:
      - git
      - maven/test:
          #command: '-X deploy -s .circleci/settings.xml'
          command: '-X --batch-mode release:prepare release:perform -s .circleci/settings.xml'